### ISSUE TITLE
including taxons with uploads

### ISSUE THREAD

**Issue by laertiades** [ginlane/spree_importer#13]
I can't figure out how to specify the taxons that pertain to products which are listed in csv file which is uploaded.  Any help would be greatly appreciated.

**Comment by weeksie** [comment]
The taxon column of the CSV can take comma separated taxon hierarchies like so:

```
Clothing -> Shirts -> Button Up, Looks -> Spring, . . .
```

That will create or match the top level as a Taxonomy and create/match the children. The `->` separator is default but can be configured (see the SpreeImporter::Config class).
