### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by thiyagarajan** [ginlane/spree_importer#21]
Template is missing
Missing template spree/admin/import_source_files/index, spree/admin/resource/index, spree/admin/base/index, spree/base/index, application/index with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder, :coffee, :rabl], :versions=>[:v1]}. Searched in: \* "d:/Projects/webstore/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_importer-432b3b13d5ab/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_hub_connector-1cea0a174fc9/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/better_spree_paypal_express-104dda73d6f1/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_social-357d58f69df1/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_marketplace-a0ab2b6006ba/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_contact_us-ec742ff30966/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_static_content-5966c16c9ef1/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_drop_ship-a264fd792586/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_fancy-43b746cdeedd/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_auth_devise-92b424f05c9f/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/gems/devise-3.2.2/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree_gateway-04c51e6bd24e/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree-119e859d3daa/frontend/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree-119e859d3daa/backend/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree-119e859d3daa/api/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/bundler/gems/spree-119e859d3daa/core/app/views" \* "c:/Ruby200/lib/ruby/gems/2.0.0/gems/kaminari-0.15.1/app/views"

**Comment by thiyagarajan** [comment]
resolved after adding haml-rails in gem file.

**Comment by weeksie** [comment]
Thanks for the heads up. haml-rails is actually included in the importer gemspec, but you might have to include it in your application's Gemfile.
