### ISSUE TITLE
Could not find gem 'spree_importer (>= 0) ruby'

### ISSUE THREAD

**Issue by ronzalo** [ginlane/spree_importer#22]
Hi,

I try to install this gem, but was not found

vagrant@precise32:/vagrant$ bundle
Fetching gem metadata from https://rubygems.org/...
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Could not find gem 'spree_importer (>= 0) ruby' in the gems available on this machine.
vagrant@precise32:/vagrant$ 

Greetings

**Comment by Allanon29** [comment]
Same problem for me.
I am using Rails 4 with Spree 2.1 stable.

Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Could not find gem 'spree_importer (>= 0) ruby' in the gems available on this machine.

**Comment by Allanon29** [comment]
Got it working like this:
gem 'spree_importer', :git => 'git://github.com/ginlane/spree_importer.git', :branch => 'master'

**Comment by weeksie** [comment]
Thanks! I'll add that to the README.
